### PR TITLE
fixing sweep names and making `open_nexradlevel2_datatree` 5x faster

### PR DESCRIPTION
**Pull request by aladinor**
Fixing names when passing sweep to `open_nexradlevel2_tree` and making it 5x faster by caching the file while extracting all datasets

- [x] Closes ##239
- [x] Changes are documented in `history.md`
- [x] Needs to wait for #238

### CODE REVIEW

**Review by kmuehlbauer — CHANGES_REQUESTED** [review]
@aladinor Sorry, I've missed the meeting today. Great work! If you can get the Nexrad notebook to work this will be ready to go!

**Comment by kmuehlbauer** [comment]
Docs failing, but this seems like a broader issue. xarray docs failing the same way. 

`403 Client Error: Forbidden for url: https://raw.githubusercontent.com/....`

I'm thinking that either GitHub changed something on their policy or some dependency in the network stack runs havoc. If there is someone out there brave enough to hunt that one down...

**Comment by kmuehlbauer** [comment]
Amazing! @aladinor :100:

**Comment by mgrover1** [comment]
This is awesome! Thanks @aladinor 👍

**Comment by kmuehlbauer** [comment]
> Docs failing, but this seems like a broader issue. xarray docs failing the same way.
> 
> `403 Client Error: Forbidden for url: https://raw.githubusercontent.com/....`
> 
> I'm thinking that either GitHub changed something on their policy or some dependency in the network stack runs havoc. If there is someone out there brave enough to hunt that one down...

Details: https://github.com/readthedocs/readthedocs.org/issues/11763

This is resolved by https://github.com/openradar/open-radar-data/pull/70 and https://github.com/openradar/open-radar-data/releases/tag/v0.4.0. 

A bit hacky, but only one source to change. :grin:

**Pull request merged**
