### PR TITLE
ENH: Add new examples using radar data on AWS s3 bucket

### PR DESCRIPTION
**Pull request by aladinor**
- [x] Tests added
- [x] Changes are documented in `history.md`

### CODE REVIEW

**Comment by mgrover1** [comment]
Thanks @aladinor - it looks like that did the trick!

**Comment by mgrover1** [comment]
@aladinor - can you add boto3 to both the `ci/unittests.yml` and `environment.yml` files?

**Comment by mgrover1** [comment]
I think the environment.yml is required too

**Comment by mgrover1** [comment]
You'll need py-art too!

**Review by mgrover1 — APPROVED** [review]
This looks great! Let's merge!

**Comment by mgrover1** [comment]
Thanks for all you work here @aladinor !

**Comment by aladinor** [comment]
Tanks @mgrover1 for your guidance!!!

**Comment by kmuehlbauer** [comment]
@aladinor Great work so far. 

It's missing in the rendered docs. @mgrover1 Is this just on my side, or is there an additional link in the docs missing.

**Comment by mgrover1** [comment]
It's missing... I can dig in and see if I can find the issue

**Comment by kmuehlbauer** [comment]
@aladinor @mgrover1 I'm not sure why the doc build fails now with these https/SSL errors while fetching data. 

It doesn't look like it is caused by the changes in this PR. Also not sure if this might be related in any case https://github.blog/2023-03-23-we-updated-our-rsa-ssh-host-key/

Maybe it's just a spurious thing. Anyway, I'll catch up tomorrow.

**Comment by kmuehlbauer** [comment]
@aladinor This was a spurious thing. This is really looking a great example. Thanks for putting this together.

https://openradar-docs--102.org.readthedocs.build/projects/xradar/en/102/

I'm no native speaker either, but spotted some typos. Maybe you can have a final read on the rendered output and change what you feel necessary.

Again, this is a great example!

**Comment by aladinor** [comment]
@kmuehlbauer and @mgrover1, thanks for putting all the effort into this. I will work on typos.

**Review by kmuehlbauer — APPROVED** [review]

**Pull request merged**
