### PR TITLE
Combined docs fixes

### PR DESCRIPTION
**Pull request by kmuehlbauer**
consumes #9 and #10

### CODE REVIEW

**Comment by kmuehlbauer** [comment]
@mgrover1 Would be nice, if we could enable the rtd pull request builds. Otherwise checking the doc build is a bit clunky. 

I've fixed the doc builds with regard to rst <-> md and activated some more sphinx-plugins. Progressing a bit on this.

**Comment by kmuehlbauer** [comment]
@scollis, @jfigui, @DanielMichelson, @mgrover1, @wolfidan

I gave the about section a shot, summarising in a few sentences the whereabouts of this project. Please have look if you find the time. We can modify/change any time.

**Comment by kmuehlbauer** [comment]
Adding the text here for easier access:
 
 _At a developer meeting held in the course of the ERAD2022 conference in Locarno, Switzerland, future plans and cross-package collaboration of the openradarscience community were intensively discussed.

The consensus was that a close collaboration that benefits the entire community can only be maximized through joint projects. So the idea of a common software project whose only task is to read and write radar data was born. The data import should include as many available data formats as possible, but the data export should be limited to the recognized standards, such as ODIM_H5 and CfRadial.

As memory representation an xarray based data model was chosen, which is internally adapted to the forthcoming standard CfRadial2.1/FM301.

Any software package that uses xarray in any way will then be able to directly use the described data model and thus quickly and easily import and export radar data. Another advantage is the easy connection to already existing open source radar processing software, like Py-ART, pyrad and wradlib._

**Comment by mgrover1** [comment]
> Adding the text here for easier access:
> 
> _At a developer meeting held in the course of the ERAD2022 conference in Locarno, Switzerland, future plans and cross-package collaboration of the openradarscience community were intensively discussed.
> 
> The consensus was that a close collaboration that benefits the entire community can only be maximized through joint projects. So the idea of a common software project whose only task is to read and write radar data was born. The data import should include as many available data formats as possible, but the data export should be limited to the recognized standards, such as ODIM_H5 and CfRadial.
> 
> As memory representation an xarray based data model was chosen, which is internally adapted to the forthcoming standard CfRadial2.1/FM301.
> 
> Any software package that uses xarray in any way will then be able to directly use the described data model and thus quickly and easily import and export radar data. Another advantage is the easy connection to already existing open source radar processing software, like Py-ART, pyrad and wradlib._

This is fantastic @kmuehlbauer ! Thank you for drafting this up/converting more documents here to markdown. My only suggest here would be to link to the different projects and documents (ex. FM301, Py-ART, wradlib, and pyrad)

**Comment by kmuehlbauer** [comment]
@mgrover1 Yes, I thought that links would be good. I'm unsure which packages I should mention/link. Maybe I'll just refer to the openradarscience projects page?

**Comment by mgrover1** [comment]
> @mgrover1 Yes, I thought that links would be good. I'm unsure which packages I should mention/link. Maybe I'll just refer to the openradarscience projects page?

I think using the ones I mentioned in that comment! Not sure if the FM301 spec is openly available

**Comment by kmuehlbauer** [comment]
I meant a link to https://openradarscience.org/pages/projects/ would catch all projects.

**Comment by kmuehlbauer** [comment]
FM301  I could link to the WMO group there.

**Comment by kmuehlbauer** [comment]
I change trains in a few minutes but have another 2 hours to update this later.

**Comment by mgrover1** [comment]
Woo! Great @kmuehlbauer - again, thanks for putting this all together. I am going to grab some dinner and can review again once you make those changes!

**Comment by kmuehlbauer** [comment]
@mgrover1 Finally, the rtd build is activate from PullRequests too. I fiddled with it over at RTD (thanks for adding me) and resynced the webhooks at GitHub. Not sure what made the difference.

For the version 999 problem. We would just need to install the package on rtd or derive the naming via git in an analogous way to setuptools_scm.

**Review by mgrover1 — APPROVED** [review]
Great!!

**Comment by kmuehlbauer** [comment]
Let's move on with this. We can change/adapt anytime.

**Comment by kmuehlbauer** [comment]
I've squashed and regrouped commits.

**Pull request merged**
