### PR TITLE
DOC: fixup installation and contributing guides

### PR DESCRIPTION
**Pull request by kmuehlbauer**
- installation.md
- CONTRIBUTING.md
- README.md
- minor fixes related to requirements and tests

### CODE REVIEW

**Comment by kmuehlbauer** [comment]
Link to docs might be missing above: https://openradar-docs--19.org.readthedocs.build/projects/xradar/en/19/

**Review by mgrover1 — APPROVED** [review]
This looks great - I like the addition of the badges + the more robust installation guide!

**Comment by mgrover1** [comment]
Good to merge?

**Comment by kmuehlbauer** [comment]
Sure, will add to history the next days....

**Pull request merged**
