### PR TITLE
Make cfradial generic

### LINKED ISSUE #42: Allow arbitrary fields to be read into the cfradial1 reader
* xradar version: 0.0.8
* Python version: 3.10
* Operating System: MacOS

### Description

I am trying to read in a file with non-standard names for variables (ex. KDP). If these fields are in the underlying netCDF file, we should pass them into the object. For now, it is silently subsetting the variables in the configuration/data model module.

### What I Did 

```python
ds = xd.io.open_cfradial1_datatree('test-pol.nc', first_dim='auto')
DataTree('root', parent=None)
│   Dimensions:              ()
│   Data variables:
│       latitude             float64 38.9
│       longitude            float64 -106.9
│       altitude             float64 3.149e+03
│       time_coverage_start  |S192 b'2022-08-25T19:46:43Z'
│       time_coverage_end    |S192 b'2022-08-25T19:47:14Z'
│       volume_number        int32 218053
│       platform_type        |S192 b'fixed'
│       instrument_type      |S192 b'radar'
│   Attributes:
│       Conventions:      CF/Radial
│       title:            weather_radar_volume
│       instrument_name:  csu.sail
│       history:          created by jrobrien on jupyter02.mcp.alcf.anl.gov at 20...
└── DataTree('sweep_0')
        Dimensions:       (azimuth: 1154, range: 675)
        Coordinates:
            time          (azimuth) datetime64[ns] 2022-08-25T19:47:14 ... 2022-08-25...
          * range         (range) float32 -118.4 -58.48 1.46 ... 4.022e+04 4.028e+04
          * azimuth       (azimuth) float32 0.002944 0.07436 0.1293 ... 359.8 359.9
            elevation     (azimuth) float32 1.011 1.011 1.011 ... 1.011 1.011 1.011
            latitude      float64 38.9
            longitude     float64 -106.9
            altitude      float64 3.149e+03
        Data variables:
            DBZ           (azimuth, range) float64 ...
            VEL           (azimuth, range) float64 ...
            ZDR           (azimuth, range) float64 ...
            PHIDP         (azimuth, range) float64 ...
            RHOHV         (azimuth, range) float64 ...
            NCP           (azimuth, range) float64 ...
            SNR           (azimuth, range) float64 ...
            sweep_number  int32 0
            fixed_angle   float32 1.011
            sweep_mode    |S192 b'azimuth_surveillance\x00\x00\x00\x00azimuth_surveil...
```

Despite there being more fields in the file, which upon using the regular `netCDF4` backend, results in

```python
<xarray.Dataset>
Dimensions:                      (time: 1154, range: 675, sweep: 1)
Coordinates:
  * time                         (time) datetime64[ns] 2022-08-25T19:46:43 .....
  * range                        (range) float32 -118.4 -58.48 ... 4.028e+04
    azimuth                      (time) float32 ...
    elevation                    (time) float32 ...
Dimensions without coordinates: sweep
Data variables: (12/31)
    DBZ                          (time, range) float64 ...
    VEL                          (time, range) float64 ...
    WIDTH                        (time, range) float64 ...
    ZDR                          (time, range) float64 ...
    PHIDP                        (time, range) float64 ...
    RHOHV                        (time, range) float64 ...
    ...                           ...
    time_coverage_end            |S192 ...
    time_reference               |S192 ...
    volume_number                int32 ...
    platform_type                |S192 ...
    instrument_type              |S192 ...
    primary_axis                 |S192 ...
Attributes:
    Conventions:      CF/Radial
    title:            weather_radar_volume
    instrument_name:  csu.sail
    field_names:      DBZ, VEL, WIDTH, ZDR, PHIDP, RHOHV, NCP, SNR, DBZhv
    history:          created by jrobrien on jupyter02.mcp.alcf.anl.gov at 20...
```

### PR DESCRIPTION
**Pull request by mgrover1**
Closes #42

### CODE REVIEW

**Review by kmuehlbauer — COMMENTED** [review]
I'm not sure why this changes every string to single ticks. AFAIK black suggests double ticks.

**Comment by mgrover1** [comment]
Good question - I can rerun black on these changes

**Comment by kmuehlbauer** [comment]
Another question would be, why does black not complain about?

**Comment by kmuehlbauer** [comment]
There is this

https://github.com/openradar/xradar/blob/main/pyproject.toml#L17

**Comment by mgrover1** [comment]
@kmuehlbauer this should be good to go

**Comment by kmuehlbauer** [comment]
Great, this looks much better now :-) I'll have a thorough review the next day.

**Comment by mgrover1** [comment]
Great! I think the one catch here is that we should strip out the coordinates stored at the root level...

**Comment by kmuehlbauer** [comment]
Yes, we should already take much care to move variables and attributes to those groups, where the standard expects them. The example data in the cfradial1 notebook is a good exercise to check this.

So the `r_calib` most likely need to be moved into a separate calibration group. There are other variables/attributes which need to be stripped/moved too. Best we be now as exact as possible with that procedure.

**Comment by kmuehlbauer** [comment]
@mgrover1 To be on the same page, this is the plain output of the CfRadial1 dataset:

```
<xarray.Dataset>
Dimensions:                           (sweep: 9, r_calib: 1, time: 4343,
                                       range: 996)
Coordinates:
  * time                              (time) datetime64[ns] 2008-06-04T00:15:...
  * range                             (range) float32 150.0 300.0 ... 1.494e+05
Dimensions without coordinates: sweep, r_calib
Data variables:
    volume_number                     int32 ...
    platform_type                     |S32 ...
    primary_axis                      |S32 ...
    status_xml                        |S1 ...
    instrument_type                   |S32 ...
    radar_antenna_gain_h              float32 ...
    radar_antenna_gain_v              float32 ...
    radar_beam_width_h                float32 ...
    radar_beam_width_v                float32 ...
    radar_rx_bandwidth                float32 ...
    time_coverage_start               |S32 ...
    time_coverage_end                 |S32 ...
    azimuth_correction                float32 ...
    elevation_correction              float32 ...
    range_correction                  float32 ...
    longitude_correction              float32 ...
    latitude_correction               float32 ...
    pressure_altitude_correction      float32 ...
    altitude_correction               float32 ...
    eastward_velocity_correction      float32 ...
    northward_velocity_correction     float32 ...
    vertical_velocity_correction      float32 ...
    heading_correction                float32 ...
    roll_correction                   float32 ...
    pitch_correction                  float32 ...
    drift_correction                  float32 ...
    rotation_correction               float32 ...
    tilt_correction                   float32 ...
    latitude                          float64 ...
    longitude                         float64 ...
    altitude                          float64 ...
    sweep_number                      (sweep) int32 ...
    sweep_mode                        (sweep) |S32 ...
    polarization_mode                 (sweep) |S32 ...
    prt_mode                          (sweep) |S32 ...
    follow_mode                       (sweep) |S32 ...
    fixed_angle                       (sweep) float32 ...
    target_scan_rate                  (sweep) float32 ...
    sweep_start_ray_index             (sweep) int32 ...
    sweep_end_ray_index               (sweep) int32 ...
    r_calib_time                      (r_calib) |S32 ...
    r_calib_pulse_width               (r_calib) timedelta64[ns] ...
    r_calib_xmit_power_h              (r_calib) float32 ...
    r_calib_xmit_power_v              (r_calib) float32 ...
    r_calib_two_way_waveguide_loss_h  (r_calib) float32 ...
    r_calib_two_way_waveguide_loss_v  (r_calib) float32 ...
    r_calib_two_way_radome_loss_h     (r_calib) float32 ...
    r_calib_two_way_radome_loss_v     (r_calib) float32 ...
    r_calib_receiver_mismatch_loss    (r_calib) float32 ...
    r_calib_radar_constant_h          (r_calib) float32 ...
    r_calib_radar_constant_v          (r_calib) float32 ...
    r_calib_antenna_gain_h            (r_calib) float32 ...
    r_calib_antenna_gain_v            (r_calib) float32 ...
    r_calib_noise_hc                  (r_calib) float32 ...
    r_calib_noise_vc                  (r_calib) float32 ...
    r_calib_noise_hx                  (r_calib) float32 ...
    r_calib_noise_vx                  (r_calib) float32 ...
    r_calib_receiver_gain_hc          (r_calib) float32 ...
    r_calib_receiver_gain_vc          (r_calib) float32 ...
    r_calib_receiver_gain_hx          (r_calib) float32 ...
    r_calib_receiver_gain_vx          (r_calib) float32 ...
    r_calib_base_dbz_1km_hc           (r_calib) float32 ...
    r_calib_base_dbz_1km_vc           (r_calib) float32 ...
    r_calib_base_dbz_1km_hx           (r_calib) float32 ...
    r_calib_base_dbz_1km_vx           (r_calib) float32 ...
    r_calib_sun_power_hc              (r_calib) float32 ...
    r_calib_sun_power_vc              (r_calib) float32 ...
    r_calib_sun_power_hx              (r_calib) float32 ...
    r_calib_sun_power_vx              (r_calib) float32 ...
    r_calib_noise_source_power_h      (r_calib) float32 ...
    r_calib_noise_source_power_v      (r_calib) float32 ...
    r_calib_power_measure_loss_h      (r_calib) float32 ...
    r_calib_power_measure_loss_v      (r_calib) float32 ...
    r_calib_coupler_forward_loss_h    (r_calib) float32 ...
    r_calib_coupler_forward_loss_v    (r_calib) float32 ...
    r_calib_zdr_correction            (r_calib) float32 ...
    r_calib_ldr_correction_h          (r_calib) float32 ...
    r_calib_ldr_correction_v          (r_calib) float32 ...
    r_calib_system_phidp              (r_calib) float32 ...
    r_calib_test_power_h              (r_calib) float32 ...
    r_calib_test_power_v              (r_calib) float32 ...
    r_calib_receiver_slope_hc         (r_calib) float32 ...
    r_calib_receiver_slope_vc         (r_calib) float32 ...
    r_calib_receiver_slope_hx         (r_calib) float32 ...
    r_calib_receiver_slope_vx         (r_calib) float32 ...
    azimuth                           (time) float32 ...
    elevation                         (time) float32 ...
    pulse_width                       (time) timedelta64[ns] ...
    prt                               (time) timedelta64[ns] ...
    prt_ratio                         (time) timedelta64[ns] ...
    nyquist_velocity                  (time) float32 ...
    unambiguous_range                 (time) float32 ...
    antenna_transition                (time) int8 ...
    n_samples                         (time) int32 ...
    r_calib_index                     (time) int8 ...
    measured_transmit_power_h         (time) float32 ...
    measured_transmit_power_v         (time) float32 ...
    scan_rate                         (time) float32 ...
    DBZ                               (time, range) float32 ...
    VR                                (time, range) float32 ...
Attributes:
    Conventions:         CF/Radial instrument_parameters radar_parameters rad...
    version:             1.2
    title:               TIMREX
    institution:         
    references:          
    source:              
    history:             
    comment:             
    instrument_name:     SPOLRVP8
    site_name:           
    scan_name:           
    scan_id:             0
    platform_is_mobile:  false
    n_gates_vary:        false
```

Here are my thoughts on data variables:

- data variables with `time` or `time`/`range` dimensions -> respective sweep group
- data variables with `sweep` dimension -> respective sweep group (or removed if not needed)
- data variables with `r_calib` dimensions -> calibration group
- other variables (eg. `radar_antenna_gain_h`, `eastward_velocity_correction`) -> root group or other sub-group???

**Comment by mgrover1** [comment]
@kmuehlbauer - I agree with your description here. Unfortunately I will not be able to work on this today, but agree.

**Comment by kmuehlbauer** [comment]
@mgrover1 I've taken a stab at this. Had to refactor substantially. I'll have a example notebook on how to map the CfRadial1 model too the CfRadial2 model. Put this in another PR next week.

**Comment by kmuehlbauer** [comment]
Extended in #45

**Pull request closed without merging**
