### PR TITLE
REL: 0.6.0

### PR DESCRIPTION
**Pull request by kmuehlbauer**
- [x] Changes are documented in `history.md`

### CODE REVIEW

**Comment by rcjackson** [comment]
Yes that is my ORCID.


From: Kai Mühlbauer ***@***.***>
Date: Friday, August 2, 2024 at 4:49 AM
To: openradar/xradar ***@***.***>
Cc: Jackson, Robert ***@***.***>, Mention ***@***.***>
Subject: Re: [openradar/xradar] REL: 0.6.0 (PR #186)
@wolfidan @rcjackson Are those your ORCID id's? Daniel - https: //orcid. org/0009-0003-9199-0109 Bobby - https: //orcid. org/0000-0003-2518-1234 I'd like to add this to the CITATION. cff. An affiliation would also be nice. For the Authors. md we
ZjQcmQRYFpfptBannerStart
This Message Is From an External Sender
This message came from outside your organization.

ZjQcmQRYFpfptBannerEnd

@wolfidan<https://urldefense.us/v3/__https:/github.com/wolfidan__;!!G_uCfscf7eWS!bIoHpgjoL6WunEKQVUwFrUKSwQ2zvLhI2jeyclQuNX18jcsBKrMqngQ5_YB1bEsno9DwmWYAxBgPGO_KInY37Cx-$> @rcjackson<https://urldefense.us/v3/__https:/github.com/rcjackson__;!!G_uCfscf7eWS!bIoHpgjoL6WunEKQVUwFrUKSwQ2zvLhI2jeyclQuNX18jcsBKrMqngQ5_YB1bEsno9DwmWYAxBgPGO_KIsvNZNAW$>

Are those your ORCID id's?

Daniel - https://orcid.org/0009-0003-9199-0109<https://urldefense.us/v3/__https:/orcid.org/0009-0003-9199-0109__;!!G_uCfscf7eWS!bIoHpgjoL6WunEKQVUwFrUKSwQ2zvLhI2jeyclQuNX18jcsBKrMqngQ5_YB1bEsno9DwmWYAxBgPGO_KIlmey-Mm$>
Bobby - https://orcid.org/0000-0003-2518-1234<https://urldefense.us/v3/__https:/orcid.org/0000-0003-2518-1234__;!!G_uCfscf7eWS!bIoHpgjoL6WunEKQVUwFrUKSwQ2zvLhI2jeyclQuNX18jcsBKrMqngQ5_YB1bEsno9DwmWYAxBgPGO_KIh2zsb9_$>

I'd like to add this to the CITATION.cff. An affiliation would also be nice. For the Authors.md we would need your corresponding email. Thanks.

@mgrover1<https://urldefense.us/v3/__https:/github.com/mgrover1__;!!G_uCfscf7eWS!bIoHpgjoL6WunEKQVUwFrUKSwQ2zvLhI2jeyclQuNX18jcsBKrMqngQ5_YB1bEsno9DwmWYAxBgPGO_KIs-Wl8Dt$> Let's check, if we can get this in next Monday, I'll update the date now.

**Comment by wolfidan** [comment]
Hi @mgrover1 ,

This is my Orchid: https://orcid.org/0009-0006-1419-0556

Affiliation should be there, otherwise it is 

Federal Office of Meteorology and Climatology MeteoSwiss: Zurich, CH

Thank you!

**Comment by kmuehlbauer** [comment]
Going to merge this now and cut a release? @mgrover1 Do you have anything to add here?

**Comment by mgrover1** [comment]
Nothing else to add here 👍 nice work everyone! Good to go!

**Pull request merged**
