### PR TITLE
Add an example on reading multiple sweeps into a single object

### LINKED ISSUE #64: Add an Example Using `open_mfdataset` with an angle preprocessing function
### Description

At the Pangeo working meeting on Friday, an xradar user suggested adding an example reading in multiple SIGMET files, applying the angle re-indexing, and reading into a single xarray object for the lowest sweep in the volume scan.

### What I Did

It would look something like this:
```python
import glob
import xradar

# Reindex function
def reindex_angles():
   ...

# List of files
sigmet_files = glob.glob('...')

# Read the data using preprocessing function
ds = xr.open_mfdataset(sigmet_files, engine='sigmet', preprocess=reindex_angles, concat_dim='volume')
```

### PR DESCRIPTION
**Pull request by mgrover1**
Closes #64 

This is a draft for now, waiting on data from `open-radar-data`

### CODE REVIEW

**Comment by kmuehlbauer** [comment]
@mgrover1 What is the status of this? If I can be of any help to get it over the line, let me know.

**Comment by mgrover1** [comment]
It is close to completion - finalizing a few things

**Comment by mgrover1** [comment]
@kmuehlbauer this is ready for review! I added in a bit using the facetgrid functionality from xarray.

**Comment by kmuehlbauer** [comment]
Sounds great, Max. I'm afk for today, but I'll review first thing tomorrow.

**Comment by kmuehlbauer** [comment]
@mgrover1 the notebook would need linking into the docs. So far I can tell from the phone.

**Review by kmuehlbauer — APPROVED** [review]
This looks very nice!

**Comment by kmuehlbauer** [comment]
@mgrover1 Please merge at your discretion. The only (stylistic) thing I'd change is wrapping the the output of datasets with `display()`.

**Comment by kmuehlbauer** [comment]
@VieuxRoblochon Could you please open a new issue describing that problem in more detail? Thanks!

**Pull request merged**
