### PR TITLE
ENH: Accessors

### PR DESCRIPTION
**Pull request by kmuehlbauer**
- builds on #20, needs rebase after #20 is merged.

- minimal implementation of accessors
- accessors showcase

### CODE REVIEW

**Review by mgrover1 — COMMENTED** [review]
Can we implement accessors at the datatree level? https://xarray-datatree.readthedocs.io/en/latest/generated/datatree.register_datatree_accessor.html?highlight=accessor

**Comment by kmuehlbauer** [comment]
Sure, as well as at the Dataset level.

Reserved for follow up PR.

**Comment by mgrover1** [comment]
> Sure, as well as at the Dataset level.
> 
> Reserved for follow up PR.

Sounds like a plan :)

**Review by mgrover1 — APPROVED** [review]
Great! I really like the example notebook included here. I think we can also go ahead and create that data repository to make accessing that data even easier!

**Comment by mgrover1** [comment]
@kmuehlbauer - I merged the other PR, can you update your main branch, and resolve these conflicts?

**Comment by kmuehlbauer** [comment]
@mgrover1 I'm AFK for a while. Do you mind doing the rebase for me?

**Comment by kmuehlbauer** [comment]
Working from the phone isn't that easy. :grimacing:

**Comment by mgrover1** [comment]
Can do :)

**Comment by mgrover1** [comment]
Fixed! Merging away @kmuehlbauer !

**Pull request merged**
