### PR TITLE
Adapt to new build process, pyproject.toml only

### LINKED ISSUE #66: Move to pure pyproject.toml builds
@mgrover1 I'm thinking about adopting pure `pyproject.toml` based builds to get rid of `setup.py`/`setup.cfg`. This would include moving linting to `ruff`. WDYT?

### PR DESCRIPTION
**Pull request by kmuehlbauer**
This moves (hopefully) everything from `setup.py`/`setup.cfg` to `pyproject.toml`. Also uses `ruff` for linting.

I've tested building locally, with success.

closes #66

### CODE REVIEW

**Comment by kmuehlbauer** [comment]
Almost smooth transition, @mgrover1. This is OK from my side.

**Review by mgrover1 — APPROVED** [review]

**Comment by kmuehlbauer** [comment]
Let's wait for the docs-build to finish. After merge we could go for a new release, just to see that the whole pipeline works.

**Comment by mgrover1** [comment]
@kmuehlbauer sounds like a plan!! Thanks for doing this - I am excited to see the speed improvments

**Comment by kmuehlbauer** [comment]
I'll update history in another (release) PR.

**Pull request merged**
