### PR TITLE
ODIM_H5 Backend

### PR DESCRIPTION
**Pull request by kmuehlbauer**
This is a direct addendum of #13. Will rebase after #13 is merged.

### CODE REVIEW

**Comment by kmuehlbauer** [comment]
Rebased on latest main.

**Comment by kmuehlbauer** [comment]
@mgrover How about adding two notebooks showing the current capabilities? Where to put them? Adding a notebooks-folder?

**Comment by mgrover1** [comment]
@kmuehlbauer let's add an `examples` directory

**Comment by kmuehlbauer** [comment]
@mgrover1 This concludes the minimal setup to read the current standards (CfRadial1/ODIM_H5). I think I'm done with this (beside the likely bugs :grinning:). Merge at your discretion. 

After merge: 
To push this a bit, we could release 0.0.5 and ask people to use it with their CfRadial1 / ODIM_H5 datasets. A conda-forge feedstock would then be fine too.

**Review by mgrover1 — APPROVED** [review]
Great!! Thanks @kmuehlbauer . I agree here - let's merge, cut a new release, and release via conda-forge. This will provide an opportunity to test.

**Pull request merged**
