### PR TITLE
REL: 0.2.0

### PR DESCRIPTION
**Pull request by kmuehlbauer**
- [x] Changes are documented in `history.md`

@egouden Please check, if you are happy with the attributions/affiliation. 
@mgrover1 I've set the date to March 22 to have enough time for responses.

### CODE REVIEW

**Review by mgrover1 — APPROVED** [review]
Looks great!

**Comment by kmuehlbauer** [comment]
@egouden I'd appreciate if you could have a look into the changes concerning your affiliation etc. Release was planned for today, but we can postpone to any later date.

**Comment by mgrover1** [comment]
@kmuehlbauer should we go ahead and merge?

**Comment by kmuehlbauer** [comment]
We have a meeting tomorrow together with @egouden. I'll sort this out tomorrow and do the release.

**Comment by mgrover1** [comment]
Sounds great!!

**Comment by egouden** [comment]
Excellent work !

**Pull request merged**
