### PR TITLE
ENH: make Furuno reader read WRN110 scn data (format 103)

### LINKED ISSUE #59: Enhance Furuno Reader to read WR110 data
* xradar version: 0.8.0

### Description

XRef: https://github.com/wradlib/wradlib/pull/606

### PR DESCRIPTION
**Pull request by kmuehlbauer**
closes #59

### CODE REVIEW

**Comment by mgrover1** [comment]
@kmuehlbauer let me know when this is ready for review!

**Comment by kmuehlbauer** [comment]
@mgrover1 I'm fine with it now. We might want to rebase merge to have the CI changes in separate commits.

I've adapted to latest black defaults and removed Python=3.8 from the matrix (as xarray etc. are doing).

**Comment by mgrover1** [comment]
@kmuehlbauer we could also have the version changes it in a separate PR?

**Review by mgrover1 — APPROVED** [review]
This looks great! I think we should go ahead and merge.

**Pull request merged**
